// Generated by kernel.wgsl.js gemmWgsl({TN:64, RN:4, f16Math:true}) -- the best-measured variant (see RESULTS.md).
enable f16;
enable subgroups;
struct Params { N: u32, K: u32, wordBase: u32, scaleBase: u32 }
@group(0) @binding(0) var<storage, read> bits: array<u32>;
@group(0) @binding(1) var<storage, read> scales: array<u32>;
@group(0) @binding(2) var<storage, read> A: array<vec4<f32>>;
@group(0) @binding(3) var<storage, read_write> Y: array<f32>;
@group(0) @binding(4) var<uniform> P: Params;

const M = 8u; const KS = 8u; const CH = 256u; const TN = 64u; const RN = 4u; const WG = 128u;
const CHV = CH / 4u;            // vec4s per activation row per chunk (64)
var<workgroup> As: array<vec4<f16>, M * CHV>;   // transposed: index = m*CHV + g*KS + kg (g = vec4 group in block 0..7)

fn trits(word: u32, sh: u32) -> vec4<f32> {
  let codes = (vec4<u32>(word >> sh) >> vec4<u32>(0u, 2u, 4u, 6u)) & vec4<u32>(3u);
  return bitcast<vec4<f32>>(codes | vec4<u32>(0x4b000000u)) - vec4<f32>(8388609.0);   // code - 1
}

@compute @workgroup_size(128)
fn main(@builtin(workgroup_id) wid: vec3<u32>, @builtin(local_invocation_id) lid3: vec3<u32>) {
  let lid = lid3.x;
  let kg = lid & (KS - 1u);
  let rg = lid / KS;
  let row0 = wid.x * TN + rg * RN;
  let BPR = P.K / 32u;
  let KV = P.K / 4u;
  let nChunks = P.K / CH;
  var acc: array<array<f32, 8>, 4>;
  for (var r = 0u; r < RN; r++) { for (var m = 0u; m < M; m++) { acc[r][m] = 0.0; } }
  for (var c = 0u; c < nChunks; c++) {
    let kc0v = c * CHV;
    for (var i = lid; i < M * CHV; i += WG) {
      let m = i / CHV; let v = i - m * CHV;
      As[m * CHV + (v & 7u) * KS + (v >> 3u)] = vec4<f16>(A[m * KV + kc0v + v]);
    }
    workgroupBarrier();
    let kb = c * KS + kg;
    var wa: array<u32, 4>; var wb: array<u32, 4>; var sc: array<f32, 4>;
    for (var r = 0u; r < RN; r++) {
      let blk = (row0 + r) * BPR + kb;
      wa[r] = bits[P.wordBase + blk * 2u];
      wb[r] = bits[P.wordBase + blk * 2u + 1u];
      sc[r] = unpack2x16float(scales[P.scaleBase + (blk >> 3u)])[(blk >> 2u) & 1u];
    }
    var part: array<array<f16, 8>, 4>;
    for (var r = 0u; r < RN; r++) { for (var m = 0u; m < M; m++) { part[r][m] = f16(0.0); } }
    for (var g = 0u; g < 8u; g++) {
      let base = g * KS + kg;
      var av: array<vec4<f16>, 8>;
      for (var m = 0u; m < M; m++) { av[m] = vec4<f16>(As[m * CHV + base]); }
      for (var r = 0u; r < RN; r++) {
        let w = vec4<f16>(trits(select(wa[r], wb[r], g >= 4u), (g & 3u) * 8u));
        for (var m = 0u; m < M; m++) { part[r][m] += dot(w, av[m]); }
      }
    }
    for (var r = 0u; r < RN; r++) { for (var m = 0u; m < M; m++) { acc[r][m] += sc[r] * f32(part[r][m]); } }
    workgroupBarrier();
  }
  for (var r = 0u; r < RN; r++) {
    for (var m = 0u; m < M; m++) {
      var v = acc[r][m];
      v += subgroupShuffleXor(v, 1u);
      v += subgroupShuffleXor(v, 2u);
      v += subgroupShuffleXor(v, 4u);
      if (kg == 0u) { Y[m * P.N + row0 + r] = v; }
    }
  }
}
