// Generated by kernel.wgsl.js gemmWgslM({M:4, TN:64, RN:4, math:"f16", aStore:"f16", unroll:true}) -- the best M=4 variant (see RESULTS.md M=4/5).
enable f16;
enable subgroups;
struct Params { N: u32, K: u32, wordBase: u32, scaleBase: u32, chunksPerSplit: u32, pad0: u32, pad1: u32, pad2: u32 }
@group(0) @binding(0) var<storage, read> bits: array<u32>;
@group(0) @binding(1) var<storage, read> scales: array<u32>;
@group(0) @binding(2) var<storage, read> A: array<vec4<f32>>;
@group(0) @binding(3) var<storage, read_write> Y: array<f32>;
@group(0) @binding(4) var<uniform> P: Params;

const M = 4u; const KS = 8u; const CH = 256u; const TN = 64u; const RN = 4u; const WG = 128u; const CHV = 64u;
var<workgroup> As: array<vec4<f16>, M * CHV>;

fn trits(word: u32, sh: u32) -> vec4<f16> {
  let codes = (vec4<u32>(word >> sh) >> vec4<u32>(0u, 2u, 4u, 6u)) & vec4<u32>(3u);
  return vec4<f16>(bitcast<vec4<f32>>(codes | vec4<u32>(0x4b000000u)) - vec4<f32>(8388609.0));
}
@compute @workgroup_size(128)
fn main(@builtin(workgroup_id) wid: vec3<u32>, @builtin(local_invocation_id) lid3: vec3<u32>) {
  let lid = lid3.x; let kg = lid & (KS - 1u); let rg = lid / KS;
  let row0 = wid.x * TN + rg * RN; let BPR = P.K / 32u; let KV = P.K / 4u;
  let c0 = wid.y * P.chunksPerSplit; let c1 = c0 + P.chunksPerSplit;
  let outBase = wid.y * (M * P.N);

  var acc0_0 = 0.0;
  var acc0_1 = 0.0;
  var acc0_2 = 0.0;
  var acc0_3 = 0.0;
  var acc1_0 = 0.0;
  var acc1_1 = 0.0;
  var acc1_2 = 0.0;
  var acc1_3 = 0.0;
  var acc2_0 = 0.0;
  var acc2_1 = 0.0;
  var acc2_2 = 0.0;
  var acc2_3 = 0.0;
  var acc3_0 = 0.0;
  var acc3_1 = 0.0;
  var acc3_2 = 0.0;
  var acc3_3 = 0.0;
  for (var c = c0; c < c1; c++) {
    let kc0v = c * CHV;
    for (var i = lid; i < M * CHV; i += WG) { let m = i / CHV; let v = i - m * CHV; As[m * CHV + (v & 7u) * KS + (v >> 3u)] = vec4<f16>(A[m * KV + kc0v + v]); }
    workgroupBarrier();
    let kb = c * KS + kg;
    let blk0 = (row0 + 0u) * BPR + kb; let wa0 = bits[P.wordBase + blk0 * 2u]; let wb0 = bits[P.wordBase + blk0 * 2u + 1u]; let sc0 = unpack2x16float(scales[P.scaleBase + (blk0 >> 3u)])[(blk0 >> 2u) & 1u];
    let blk1 = (row0 + 1u) * BPR + kb; let wa1 = bits[P.wordBase + blk1 * 2u]; let wb1 = bits[P.wordBase + blk1 * 2u + 1u]; let sc1 = unpack2x16float(scales[P.scaleBase + (blk1 >> 3u)])[(blk1 >> 2u) & 1u];
    let blk2 = (row0 + 2u) * BPR + kb; let wa2 = bits[P.wordBase + blk2 * 2u]; let wb2 = bits[P.wordBase + blk2 * 2u + 1u]; let sc2 = unpack2x16float(scales[P.scaleBase + (blk2 >> 3u)])[(blk2 >> 2u) & 1u];
    let blk3 = (row0 + 3u) * BPR + kb; let wa3 = bits[P.wordBase + blk3 * 2u]; let wb3 = bits[P.wordBase + blk3 * 2u + 1u]; let sc3 = unpack2x16float(scales[P.scaleBase + (blk3 >> 3u)])[(blk3 >> 2u) & 1u];
    var p0_0 = 0.0h;
    var p0_1 = 0.0h;
    var p0_2 = 0.0h;
    var p0_3 = 0.0h;
    var p1_0 = 0.0h;
    var p1_1 = 0.0h;
    var p1_2 = 0.0h;
    var p1_3 = 0.0h;
    var p2_0 = 0.0h;
    var p2_1 = 0.0h;
    var p2_2 = 0.0h;
    var p2_3 = 0.0h;
    var p3_0 = 0.0h;
    var p3_1 = 0.0h;
    var p3_2 = 0.0h;
    var p3_3 = 0.0h;
    {
      let a0 = vec4<f16>(As[0u + kg]);
      let a1 = vec4<f16>(As[64u + kg]);
      let a2 = vec4<f16>(As[128u + kg]);
      let a3 = vec4<f16>(As[192u + kg]);
      let w0 = trits(wa0, 0u);
      p0_0 += dot(w0, a0);
      p0_1 += dot(w0, a1);
      p0_2 += dot(w0, a2);
      p0_3 += dot(w0, a3);
      let w1 = trits(wa1, 0u);
      p1_0 += dot(w1, a0);
      p1_1 += dot(w1, a1);
      p1_2 += dot(w1, a2);
      p1_3 += dot(w1, a3);
      let w2 = trits(wa2, 0u);
      p2_0 += dot(w2, a0);
      p2_1 += dot(w2, a1);
      p2_2 += dot(w2, a2);
      p2_3 += dot(w2, a3);
      let w3 = trits(wa3, 0u);
      p3_0 += dot(w3, a0);
      p3_1 += dot(w3, a1);
      p3_2 += dot(w3, a2);
      p3_3 += dot(w3, a3);
    }
    {
      let a0 = vec4<f16>(As[8u + kg]);
      let a1 = vec4<f16>(As[72u + kg]);
      let a2 = vec4<f16>(As[136u + kg]);
      let a3 = vec4<f16>(As[200u + kg]);
      let w0 = trits(wa0, 8u);
      p0_0 += dot(w0, a0);
      p0_1 += dot(w0, a1);
      p0_2 += dot(w0, a2);
      p0_3 += dot(w0, a3);
      let w1 = trits(wa1, 8u);
      p1_0 += dot(w1, a0);
      p1_1 += dot(w1, a1);
      p1_2 += dot(w1, a2);
      p1_3 += dot(w1, a3);
      let w2 = trits(wa2, 8u);
      p2_0 += dot(w2, a0);
      p2_1 += dot(w2, a1);
      p2_2 += dot(w2, a2);
      p2_3 += dot(w2, a3);
      let w3 = trits(wa3, 8u);
      p3_0 += dot(w3, a0);
      p3_1 += dot(w3, a1);
      p3_2 += dot(w3, a2);
      p3_3 += dot(w3, a3);
    }
    {
      let a0 = vec4<f16>(As[16u + kg]);
      let a1 = vec4<f16>(As[80u + kg]);
      let a2 = vec4<f16>(As[144u + kg]);
      let a3 = vec4<f16>(As[208u + kg]);
      let w0 = trits(wa0, 16u);
      p0_0 += dot(w0, a0);
      p0_1 += dot(w0, a1);
      p0_2 += dot(w0, a2);
      p0_3 += dot(w0, a3);
      let w1 = trits(wa1, 16u);
      p1_0 += dot(w1, a0);
      p1_1 += dot(w1, a1);
      p1_2 += dot(w1, a2);
      p1_3 += dot(w1, a3);
      let w2 = trits(wa2, 16u);
      p2_0 += dot(w2, a0);
      p2_1 += dot(w2, a1);
      p2_2 += dot(w2, a2);
      p2_3 += dot(w2, a3);
      let w3 = trits(wa3, 16u);
      p3_0 += dot(w3, a0);
      p3_1 += dot(w3, a1);
      p3_2 += dot(w3, a2);
      p3_3 += dot(w3, a3);
    }
    {
      let a0 = vec4<f16>(As[24u + kg]);
      let a1 = vec4<f16>(As[88u + kg]);
      let a2 = vec4<f16>(As[152u + kg]);
      let a3 = vec4<f16>(As[216u + kg]);
      let w0 = trits(wa0, 24u);
      p0_0 += dot(w0, a0);
      p0_1 += dot(w0, a1);
      p0_2 += dot(w0, a2);
      p0_3 += dot(w0, a3);
      let w1 = trits(wa1, 24u);
      p1_0 += dot(w1, a0);
      p1_1 += dot(w1, a1);
      p1_2 += dot(w1, a2);
      p1_3 += dot(w1, a3);
      let w2 = trits(wa2, 24u);
      p2_0 += dot(w2, a0);
      p2_1 += dot(w2, a1);
      p2_2 += dot(w2, a2);
      p2_3 += dot(w2, a3);
      let w3 = trits(wa3, 24u);
      p3_0 += dot(w3, a0);
      p3_1 += dot(w3, a1);
      p3_2 += dot(w3, a2);
      p3_3 += dot(w3, a3);
    }
    {
      let a0 = vec4<f16>(As[32u + kg]);
      let a1 = vec4<f16>(As[96u + kg]);
      let a2 = vec4<f16>(As[160u + kg]);
      let a3 = vec4<f16>(As[224u + kg]);
      let w0 = trits(wb0, 0u);
      p0_0 += dot(w0, a0);
      p0_1 += dot(w0, a1);
      p0_2 += dot(w0, a2);
      p0_3 += dot(w0, a3);
      let w1 = trits(wb1, 0u);
      p1_0 += dot(w1, a0);
      p1_1 += dot(w1, a1);
      p1_2 += dot(w1, a2);
      p1_3 += dot(w1, a3);
      let w2 = trits(wb2, 0u);
      p2_0 += dot(w2, a0);
      p2_1 += dot(w2, a1);
      p2_2 += dot(w2, a2);
      p2_3 += dot(w2, a3);
      let w3 = trits(wb3, 0u);
      p3_0 += dot(w3, a0);
      p3_1 += dot(w3, a1);
      p3_2 += dot(w3, a2);
      p3_3 += dot(w3, a3);
    }
    {
      let a0 = vec4<f16>(As[40u + kg]);
      let a1 = vec4<f16>(As[104u + kg]);
      let a2 = vec4<f16>(As[168u + kg]);
      let a3 = vec4<f16>(As[232u + kg]);
      let w0 = trits(wb0, 8u);
      p0_0 += dot(w0, a0);
      p0_1 += dot(w0, a1);
      p0_2 += dot(w0, a2);
      p0_3 += dot(w0, a3);
      let w1 = trits(wb1, 8u);
      p1_0 += dot(w1, a0);
      p1_1 += dot(w1, a1);
      p1_2 += dot(w1, a2);
      p1_3 += dot(w1, a3);
      let w2 = trits(wb2, 8u);
      p2_0 += dot(w2, a0);
      p2_1 += dot(w2, a1);
      p2_2 += dot(w2, a2);
      p2_3 += dot(w2, a3);
      let w3 = trits(wb3, 8u);
      p3_0 += dot(w3, a0);
      p3_1 += dot(w3, a1);
      p3_2 += dot(w3, a2);
      p3_3 += dot(w3, a3);
    }
    {
      let a0 = vec4<f16>(As[48u + kg]);
      let a1 = vec4<f16>(As[112u + kg]);
      let a2 = vec4<f16>(As[176u + kg]);
      let a3 = vec4<f16>(As[240u + kg]);
      let w0 = trits(wb0, 16u);
      p0_0 += dot(w0, a0);
      p0_1 += dot(w0, a1);
      p0_2 += dot(w0, a2);
      p0_3 += dot(w0, a3);
      let w1 = trits(wb1, 16u);
      p1_0 += dot(w1, a0);
      p1_1 += dot(w1, a1);
      p1_2 += dot(w1, a2);
      p1_3 += dot(w1, a3);
      let w2 = trits(wb2, 16u);
      p2_0 += dot(w2, a0);
      p2_1 += dot(w2, a1);
      p2_2 += dot(w2, a2);
      p2_3 += dot(w2, a3);
      let w3 = trits(wb3, 16u);
      p3_0 += dot(w3, a0);
      p3_1 += dot(w3, a1);
      p3_2 += dot(w3, a2);
      p3_3 += dot(w3, a3);
    }
    {
      let a0 = vec4<f16>(As[56u + kg]);
      let a1 = vec4<f16>(As[120u + kg]);
      let a2 = vec4<f16>(As[184u + kg]);
      let a3 = vec4<f16>(As[248u + kg]);
      let w0 = trits(wb0, 24u);
      p0_0 += dot(w0, a0);
      p0_1 += dot(w0, a1);
      p0_2 += dot(w0, a2);
      p0_3 += dot(w0, a3);
      let w1 = trits(wb1, 24u);
      p1_0 += dot(w1, a0);
      p1_1 += dot(w1, a1);
      p1_2 += dot(w1, a2);
      p1_3 += dot(w1, a3);
      let w2 = trits(wb2, 24u);
      p2_0 += dot(w2, a0);
      p2_1 += dot(w2, a1);
      p2_2 += dot(w2, a2);
      p2_3 += dot(w2, a3);
      let w3 = trits(wb3, 24u);
      p3_0 += dot(w3, a0);
      p3_1 += dot(w3, a1);
      p3_2 += dot(w3, a2);
      p3_3 += dot(w3, a3);
    }
    acc0_0 += sc0 * f32(p0_0);
    acc0_1 += sc0 * f32(p0_1);
    acc0_2 += sc0 * f32(p0_2);
    acc0_3 += sc0 * f32(p0_3);
    acc1_0 += sc1 * f32(p1_0);
    acc1_1 += sc1 * f32(p1_1);
    acc1_2 += sc1 * f32(p1_2);
    acc1_3 += sc1 * f32(p1_3);
    acc2_0 += sc2 * f32(p2_0);
    acc2_1 += sc2 * f32(p2_1);
    acc2_2 += sc2 * f32(p2_2);
    acc2_3 += sc2 * f32(p2_3);
    acc3_0 += sc3 * f32(p3_0);
    acc3_1 += sc3 * f32(p3_1);
    acc3_2 += sc3 * f32(p3_2);
    acc3_3 += sc3 * f32(p3_3);
    workgroupBarrier();
  }
  { var v = acc0_0; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 0u * P.N + row0 + 0u] = v; } }
  { var v = acc0_1; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 1u * P.N + row0 + 0u] = v; } }
  { var v = acc0_2; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 2u * P.N + row0 + 0u] = v; } }
  { var v = acc0_3; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 3u * P.N + row0 + 0u] = v; } }
  { var v = acc1_0; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 0u * P.N + row0 + 1u] = v; } }
  { var v = acc1_1; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 1u * P.N + row0 + 1u] = v; } }
  { var v = acc1_2; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 2u * P.N + row0 + 1u] = v; } }
  { var v = acc1_3; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 3u * P.N + row0 + 1u] = v; } }
  { var v = acc2_0; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 0u * P.N + row0 + 2u] = v; } }
  { var v = acc2_1; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 1u * P.N + row0 + 2u] = v; } }
  { var v = acc2_2; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 2u * P.N + row0 + 2u] = v; } }
  { var v = acc2_3; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 3u * P.N + row0 + 2u] = v; } }
  { var v = acc3_0; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 0u * P.N + row0 + 3u] = v; } }
  { var v = acc3_1; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 1u * P.N + row0 + 3u] = v; } }
  { var v = acc3_2; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 2u * P.N + row0 + 3u] = v; } }
  { var v = acc3_3; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[outBase + 3u * P.N + row0 + 3u] = v; } }
}
