// Generated by kernel.wgsl.js gemmWgslV2({TN:64, RN:4, math:"f32", aStore:"f32"}) -- the f32-exact variant (see RESULTS.md).
enable subgroups;
struct Params { N: u32, K: u32, wordBase: u32, scaleBase: u32 }
@group(0) @binding(0) var<storage, read> bits: array<u32>;
@group(0) @binding(1) var<storage, read> scales: array<u32>;
@group(0) @binding(2) var<storage, read> A: array<vec4<f32>>;
@group(0) @binding(3) var<storage, read_write> Y: array<f32>;
@group(0) @binding(4) var<uniform> P: Params;
const M = 8u; const KS = 8u; const CH = 256u; const TN = 64u; const RN = 4u; const WG = 128u; const CHV = CH / 4u;
var<workgroup> As: array<vec4<f32>, M * CHV>;
fn trits(word: u32, sh: u32) -> vec4<f32> {
  let codes = (vec4<u32>(word >> sh) >> vec4<u32>(0u, 2u, 4u, 6u)) & vec4<u32>(3u);
  return bitcast<vec4<f32>>(codes | vec4<u32>(0x4b000000u)) - vec4<f32>(8388609.0);
}
@compute @workgroup_size(128)
fn main(@builtin(workgroup_id) wid: vec3<u32>, @builtin(local_invocation_id) lid3: vec3<u32>) {
  let lid = lid3.x; let kg = lid & (KS - 1u); let rg = lid / KS;
  let row0 = wid.x * TN + rg * RN; let BPR = P.K / 32u; let KV = P.K / 4u; let nChunks = P.K / CH;
  var acc0_0 = 0.0;
  var acc0_1 = 0.0;
  var acc0_2 = 0.0;
  var acc0_3 = 0.0;
  var acc0_4 = 0.0;
  var acc0_5 = 0.0;
  var acc0_6 = 0.0;
  var acc0_7 = 0.0;
  var acc1_0 = 0.0;
  var acc1_1 = 0.0;
  var acc1_2 = 0.0;
  var acc1_3 = 0.0;
  var acc1_4 = 0.0;
  var acc1_5 = 0.0;
  var acc1_6 = 0.0;
  var acc1_7 = 0.0;
  var acc2_0 = 0.0;
  var acc2_1 = 0.0;
  var acc2_2 = 0.0;
  var acc2_3 = 0.0;
  var acc2_4 = 0.0;
  var acc2_5 = 0.0;
  var acc2_6 = 0.0;
  var acc2_7 = 0.0;
  var acc3_0 = 0.0;
  var acc3_1 = 0.0;
  var acc3_2 = 0.0;
  var acc3_3 = 0.0;
  var acc3_4 = 0.0;
  var acc3_5 = 0.0;
  var acc3_6 = 0.0;
  var acc3_7 = 0.0;
  for (var c = 0u; c < nChunks; c++) {
    let kc0v = c * CHV;
    for (var i = lid; i < M * CHV; i += WG) { let m = i / CHV; let v = i - m * CHV; As[m * CHV + (v & 7u) * KS + (v >> 3u)] = vec4<f32>(A[m * KV + kc0v + v]); }
    workgroupBarrier();
    let kb = c * KS + kg;
    let blk0 = (row0 + 0u) * BPR + kb; let wa0 = bits[P.wordBase + blk0 * 2u]; let wb0 = bits[P.wordBase + blk0 * 2u + 1u]; let sc0 = f32(unpack2x16float(scales[P.scaleBase + (blk0 >> 3u)])[(blk0 >> 2u) & 1u]);
    let blk1 = (row0 + 1u) * BPR + kb; let wa1 = bits[P.wordBase + blk1 * 2u]; let wb1 = bits[P.wordBase + blk1 * 2u + 1u]; let sc1 = f32(unpack2x16float(scales[P.scaleBase + (blk1 >> 3u)])[(blk1 >> 2u) & 1u]);
    let blk2 = (row0 + 2u) * BPR + kb; let wa2 = bits[P.wordBase + blk2 * 2u]; let wb2 = bits[P.wordBase + blk2 * 2u + 1u]; let sc2 = f32(unpack2x16float(scales[P.scaleBase + (blk2 >> 3u)])[(blk2 >> 2u) & 1u]);
    let blk3 = (row0 + 3u) * BPR + kb; let wa3 = bits[P.wordBase + blk3 * 2u]; let wb3 = bits[P.wordBase + blk3 * 2u + 1u]; let sc3 = f32(unpack2x16float(scales[P.scaleBase + (blk3 >> 3u)])[(blk3 >> 2u) & 1u]);
    {
      let a0 = vec4<f32>(As[0u + 0u + kg]);
      let a1 = vec4<f32>(As[64u + 0u + kg]);
      let a2 = vec4<f32>(As[128u + 0u + kg]);
      let a3 = vec4<f32>(As[192u + 0u + kg]);
      let a4 = vec4<f32>(As[256u + 0u + kg]);
      let a5 = vec4<f32>(As[320u + 0u + kg]);
      let a6 = vec4<f32>(As[384u + 0u + kg]);
      let a7 = vec4<f32>(As[448u + 0u + kg]);
      let w0 = vec4<f32>(trits(wa0, 0u)) * sc0;
      acc0_0 += f32(dot(w0, a0));
      acc0_1 += f32(dot(w0, a1));
      acc0_2 += f32(dot(w0, a2));
      acc0_3 += f32(dot(w0, a3));
      acc0_4 += f32(dot(w0, a4));
      acc0_5 += f32(dot(w0, a5));
      acc0_6 += f32(dot(w0, a6));
      acc0_7 += f32(dot(w0, a7));
      let w1 = vec4<f32>(trits(wa1, 0u)) * sc1;
      acc1_0 += f32(dot(w1, a0));
      acc1_1 += f32(dot(w1, a1));
      acc1_2 += f32(dot(w1, a2));
      acc1_3 += f32(dot(w1, a3));
      acc1_4 += f32(dot(w1, a4));
      acc1_5 += f32(dot(w1, a5));
      acc1_6 += f32(dot(w1, a6));
      acc1_7 += f32(dot(w1, a7));
      let w2 = vec4<f32>(trits(wa2, 0u)) * sc2;
      acc2_0 += f32(dot(w2, a0));
      acc2_1 += f32(dot(w2, a1));
      acc2_2 += f32(dot(w2, a2));
      acc2_3 += f32(dot(w2, a3));
      acc2_4 += f32(dot(w2, a4));
      acc2_5 += f32(dot(w2, a5));
      acc2_6 += f32(dot(w2, a6));
      acc2_7 += f32(dot(w2, a7));
      let w3 = vec4<f32>(trits(wa3, 0u)) * sc3;
      acc3_0 += f32(dot(w3, a0));
      acc3_1 += f32(dot(w3, a1));
      acc3_2 += f32(dot(w3, a2));
      acc3_3 += f32(dot(w3, a3));
      acc3_4 += f32(dot(w3, a4));
      acc3_5 += f32(dot(w3, a5));
      acc3_6 += f32(dot(w3, a6));
      acc3_7 += f32(dot(w3, a7));
    }
    {
      let a0 = vec4<f32>(As[0u + 8u + kg]);
      let a1 = vec4<f32>(As[64u + 8u + kg]);
      let a2 = vec4<f32>(As[128u + 8u + kg]);
      let a3 = vec4<f32>(As[192u + 8u + kg]);
      let a4 = vec4<f32>(As[256u + 8u + kg]);
      let a5 = vec4<f32>(As[320u + 8u + kg]);
      let a6 = vec4<f32>(As[384u + 8u + kg]);
      let a7 = vec4<f32>(As[448u + 8u + kg]);
      let w0 = vec4<f32>(trits(wa0, 8u)) * sc0;
      acc0_0 += f32(dot(w0, a0));
      acc0_1 += f32(dot(w0, a1));
      acc0_2 += f32(dot(w0, a2));
      acc0_3 += f32(dot(w0, a3));
      acc0_4 += f32(dot(w0, a4));
      acc0_5 += f32(dot(w0, a5));
      acc0_6 += f32(dot(w0, a6));
      acc0_7 += f32(dot(w0, a7));
      let w1 = vec4<f32>(trits(wa1, 8u)) * sc1;
      acc1_0 += f32(dot(w1, a0));
      acc1_1 += f32(dot(w1, a1));
      acc1_2 += f32(dot(w1, a2));
      acc1_3 += f32(dot(w1, a3));
      acc1_4 += f32(dot(w1, a4));
      acc1_5 += f32(dot(w1, a5));
      acc1_6 += f32(dot(w1, a6));
      acc1_7 += f32(dot(w1, a7));
      let w2 = vec4<f32>(trits(wa2, 8u)) * sc2;
      acc2_0 += f32(dot(w2, a0));
      acc2_1 += f32(dot(w2, a1));
      acc2_2 += f32(dot(w2, a2));
      acc2_3 += f32(dot(w2, a3));
      acc2_4 += f32(dot(w2, a4));
      acc2_5 += f32(dot(w2, a5));
      acc2_6 += f32(dot(w2, a6));
      acc2_7 += f32(dot(w2, a7));
      let w3 = vec4<f32>(trits(wa3, 8u)) * sc3;
      acc3_0 += f32(dot(w3, a0));
      acc3_1 += f32(dot(w3, a1));
      acc3_2 += f32(dot(w3, a2));
      acc3_3 += f32(dot(w3, a3));
      acc3_4 += f32(dot(w3, a4));
      acc3_5 += f32(dot(w3, a5));
      acc3_6 += f32(dot(w3, a6));
      acc3_7 += f32(dot(w3, a7));
    }
    {
      let a0 = vec4<f32>(As[0u + 16u + kg]);
      let a1 = vec4<f32>(As[64u + 16u + kg]);
      let a2 = vec4<f32>(As[128u + 16u + kg]);
      let a3 = vec4<f32>(As[192u + 16u + kg]);
      let a4 = vec4<f32>(As[256u + 16u + kg]);
      let a5 = vec4<f32>(As[320u + 16u + kg]);
      let a6 = vec4<f32>(As[384u + 16u + kg]);
      let a7 = vec4<f32>(As[448u + 16u + kg]);
      let w0 = vec4<f32>(trits(wa0, 16u)) * sc0;
      acc0_0 += f32(dot(w0, a0));
      acc0_1 += f32(dot(w0, a1));
      acc0_2 += f32(dot(w0, a2));
      acc0_3 += f32(dot(w0, a3));
      acc0_4 += f32(dot(w0, a4));
      acc0_5 += f32(dot(w0, a5));
      acc0_6 += f32(dot(w0, a6));
      acc0_7 += f32(dot(w0, a7));
      let w1 = vec4<f32>(trits(wa1, 16u)) * sc1;
      acc1_0 += f32(dot(w1, a0));
      acc1_1 += f32(dot(w1, a1));
      acc1_2 += f32(dot(w1, a2));
      acc1_3 += f32(dot(w1, a3));
      acc1_4 += f32(dot(w1, a4));
      acc1_5 += f32(dot(w1, a5));
      acc1_6 += f32(dot(w1, a6));
      acc1_7 += f32(dot(w1, a7));
      let w2 = vec4<f32>(trits(wa2, 16u)) * sc2;
      acc2_0 += f32(dot(w2, a0));
      acc2_1 += f32(dot(w2, a1));
      acc2_2 += f32(dot(w2, a2));
      acc2_3 += f32(dot(w2, a3));
      acc2_4 += f32(dot(w2, a4));
      acc2_5 += f32(dot(w2, a5));
      acc2_6 += f32(dot(w2, a6));
      acc2_7 += f32(dot(w2, a7));
      let w3 = vec4<f32>(trits(wa3, 16u)) * sc3;
      acc3_0 += f32(dot(w3, a0));
      acc3_1 += f32(dot(w3, a1));
      acc3_2 += f32(dot(w3, a2));
      acc3_3 += f32(dot(w3, a3));
      acc3_4 += f32(dot(w3, a4));
      acc3_5 += f32(dot(w3, a5));
      acc3_6 += f32(dot(w3, a6));
      acc3_7 += f32(dot(w3, a7));
    }
    {
      let a0 = vec4<f32>(As[0u + 24u + kg]);
      let a1 = vec4<f32>(As[64u + 24u + kg]);
      let a2 = vec4<f32>(As[128u + 24u + kg]);
      let a3 = vec4<f32>(As[192u + 24u + kg]);
      let a4 = vec4<f32>(As[256u + 24u + kg]);
      let a5 = vec4<f32>(As[320u + 24u + kg]);
      let a6 = vec4<f32>(As[384u + 24u + kg]);
      let a7 = vec4<f32>(As[448u + 24u + kg]);
      let w0 = vec4<f32>(trits(wa0, 24u)) * sc0;
      acc0_0 += f32(dot(w0, a0));
      acc0_1 += f32(dot(w0, a1));
      acc0_2 += f32(dot(w0, a2));
      acc0_3 += f32(dot(w0, a3));
      acc0_4 += f32(dot(w0, a4));
      acc0_5 += f32(dot(w0, a5));
      acc0_6 += f32(dot(w0, a6));
      acc0_7 += f32(dot(w0, a7));
      let w1 = vec4<f32>(trits(wa1, 24u)) * sc1;
      acc1_0 += f32(dot(w1, a0));
      acc1_1 += f32(dot(w1, a1));
      acc1_2 += f32(dot(w1, a2));
      acc1_3 += f32(dot(w1, a3));
      acc1_4 += f32(dot(w1, a4));
      acc1_5 += f32(dot(w1, a5));
      acc1_6 += f32(dot(w1, a6));
      acc1_7 += f32(dot(w1, a7));
      let w2 = vec4<f32>(trits(wa2, 24u)) * sc2;
      acc2_0 += f32(dot(w2, a0));
      acc2_1 += f32(dot(w2, a1));
      acc2_2 += f32(dot(w2, a2));
      acc2_3 += f32(dot(w2, a3));
      acc2_4 += f32(dot(w2, a4));
      acc2_5 += f32(dot(w2, a5));
      acc2_6 += f32(dot(w2, a6));
      acc2_7 += f32(dot(w2, a7));
      let w3 = vec4<f32>(trits(wa3, 24u)) * sc3;
      acc3_0 += f32(dot(w3, a0));
      acc3_1 += f32(dot(w3, a1));
      acc3_2 += f32(dot(w3, a2));
      acc3_3 += f32(dot(w3, a3));
      acc3_4 += f32(dot(w3, a4));
      acc3_5 += f32(dot(w3, a5));
      acc3_6 += f32(dot(w3, a6));
      acc3_7 += f32(dot(w3, a7));
    }
    {
      let a0 = vec4<f32>(As[0u + 32u + kg]);
      let a1 = vec4<f32>(As[64u + 32u + kg]);
      let a2 = vec4<f32>(As[128u + 32u + kg]);
      let a3 = vec4<f32>(As[192u + 32u + kg]);
      let a4 = vec4<f32>(As[256u + 32u + kg]);
      let a5 = vec4<f32>(As[320u + 32u + kg]);
      let a6 = vec4<f32>(As[384u + 32u + kg]);
      let a7 = vec4<f32>(As[448u + 32u + kg]);
      let w0 = vec4<f32>(trits(wb0, 0u)) * sc0;
      acc0_0 += f32(dot(w0, a0));
      acc0_1 += f32(dot(w0, a1));
      acc0_2 += f32(dot(w0, a2));
      acc0_3 += f32(dot(w0, a3));
      acc0_4 += f32(dot(w0, a4));
      acc0_5 += f32(dot(w0, a5));
      acc0_6 += f32(dot(w0, a6));
      acc0_7 += f32(dot(w0, a7));
      let w1 = vec4<f32>(trits(wb1, 0u)) * sc1;
      acc1_0 += f32(dot(w1, a0));
      acc1_1 += f32(dot(w1, a1));
      acc1_2 += f32(dot(w1, a2));
      acc1_3 += f32(dot(w1, a3));
      acc1_4 += f32(dot(w1, a4));
      acc1_5 += f32(dot(w1, a5));
      acc1_6 += f32(dot(w1, a6));
      acc1_7 += f32(dot(w1, a7));
      let w2 = vec4<f32>(trits(wb2, 0u)) * sc2;
      acc2_0 += f32(dot(w2, a0));
      acc2_1 += f32(dot(w2, a1));
      acc2_2 += f32(dot(w2, a2));
      acc2_3 += f32(dot(w2, a3));
      acc2_4 += f32(dot(w2, a4));
      acc2_5 += f32(dot(w2, a5));
      acc2_6 += f32(dot(w2, a6));
      acc2_7 += f32(dot(w2, a7));
      let w3 = vec4<f32>(trits(wb3, 0u)) * sc3;
      acc3_0 += f32(dot(w3, a0));
      acc3_1 += f32(dot(w3, a1));
      acc3_2 += f32(dot(w3, a2));
      acc3_3 += f32(dot(w3, a3));
      acc3_4 += f32(dot(w3, a4));
      acc3_5 += f32(dot(w3, a5));
      acc3_6 += f32(dot(w3, a6));
      acc3_7 += f32(dot(w3, a7));
    }
    {
      let a0 = vec4<f32>(As[0u + 40u + kg]);
      let a1 = vec4<f32>(As[64u + 40u + kg]);
      let a2 = vec4<f32>(As[128u + 40u + kg]);
      let a3 = vec4<f32>(As[192u + 40u + kg]);
      let a4 = vec4<f32>(As[256u + 40u + kg]);
      let a5 = vec4<f32>(As[320u + 40u + kg]);
      let a6 = vec4<f32>(As[384u + 40u + kg]);
      let a7 = vec4<f32>(As[448u + 40u + kg]);
      let w0 = vec4<f32>(trits(wb0, 8u)) * sc0;
      acc0_0 += f32(dot(w0, a0));
      acc0_1 += f32(dot(w0, a1));
      acc0_2 += f32(dot(w0, a2));
      acc0_3 += f32(dot(w0, a3));
      acc0_4 += f32(dot(w0, a4));
      acc0_5 += f32(dot(w0, a5));
      acc0_6 += f32(dot(w0, a6));
      acc0_7 += f32(dot(w0, a7));
      let w1 = vec4<f32>(trits(wb1, 8u)) * sc1;
      acc1_0 += f32(dot(w1, a0));
      acc1_1 += f32(dot(w1, a1));
      acc1_2 += f32(dot(w1, a2));
      acc1_3 += f32(dot(w1, a3));
      acc1_4 += f32(dot(w1, a4));
      acc1_5 += f32(dot(w1, a5));
      acc1_6 += f32(dot(w1, a6));
      acc1_7 += f32(dot(w1, a7));
      let w2 = vec4<f32>(trits(wb2, 8u)) * sc2;
      acc2_0 += f32(dot(w2, a0));
      acc2_1 += f32(dot(w2, a1));
      acc2_2 += f32(dot(w2, a2));
      acc2_3 += f32(dot(w2, a3));
      acc2_4 += f32(dot(w2, a4));
      acc2_5 += f32(dot(w2, a5));
      acc2_6 += f32(dot(w2, a6));
      acc2_7 += f32(dot(w2, a7));
      let w3 = vec4<f32>(trits(wb3, 8u)) * sc3;
      acc3_0 += f32(dot(w3, a0));
      acc3_1 += f32(dot(w3, a1));
      acc3_2 += f32(dot(w3, a2));
      acc3_3 += f32(dot(w3, a3));
      acc3_4 += f32(dot(w3, a4));
      acc3_5 += f32(dot(w3, a5));
      acc3_6 += f32(dot(w3, a6));
      acc3_7 += f32(dot(w3, a7));
    }
    {
      let a0 = vec4<f32>(As[0u + 48u + kg]);
      let a1 = vec4<f32>(As[64u + 48u + kg]);
      let a2 = vec4<f32>(As[128u + 48u + kg]);
      let a3 = vec4<f32>(As[192u + 48u + kg]);
      let a4 = vec4<f32>(As[256u + 48u + kg]);
      let a5 = vec4<f32>(As[320u + 48u + kg]);
      let a6 = vec4<f32>(As[384u + 48u + kg]);
      let a7 = vec4<f32>(As[448u + 48u + kg]);
      let w0 = vec4<f32>(trits(wb0, 16u)) * sc0;
      acc0_0 += f32(dot(w0, a0));
      acc0_1 += f32(dot(w0, a1));
      acc0_2 += f32(dot(w0, a2));
      acc0_3 += f32(dot(w0, a3));
      acc0_4 += f32(dot(w0, a4));
      acc0_5 += f32(dot(w0, a5));
      acc0_6 += f32(dot(w0, a6));
      acc0_7 += f32(dot(w0, a7));
      let w1 = vec4<f32>(trits(wb1, 16u)) * sc1;
      acc1_0 += f32(dot(w1, a0));
      acc1_1 += f32(dot(w1, a1));
      acc1_2 += f32(dot(w1, a2));
      acc1_3 += f32(dot(w1, a3));
      acc1_4 += f32(dot(w1, a4));
      acc1_5 += f32(dot(w1, a5));
      acc1_6 += f32(dot(w1, a6));
      acc1_7 += f32(dot(w1, a7));
      let w2 = vec4<f32>(trits(wb2, 16u)) * sc2;
      acc2_0 += f32(dot(w2, a0));
      acc2_1 += f32(dot(w2, a1));
      acc2_2 += f32(dot(w2, a2));
      acc2_3 += f32(dot(w2, a3));
      acc2_4 += f32(dot(w2, a4));
      acc2_5 += f32(dot(w2, a5));
      acc2_6 += f32(dot(w2, a6));
      acc2_7 += f32(dot(w2, a7));
      let w3 = vec4<f32>(trits(wb3, 16u)) * sc3;
      acc3_0 += f32(dot(w3, a0));
      acc3_1 += f32(dot(w3, a1));
      acc3_2 += f32(dot(w3, a2));
      acc3_3 += f32(dot(w3, a3));
      acc3_4 += f32(dot(w3, a4));
      acc3_5 += f32(dot(w3, a5));
      acc3_6 += f32(dot(w3, a6));
      acc3_7 += f32(dot(w3, a7));
    }
    {
      let a0 = vec4<f32>(As[0u + 56u + kg]);
      let a1 = vec4<f32>(As[64u + 56u + kg]);
      let a2 = vec4<f32>(As[128u + 56u + kg]);
      let a3 = vec4<f32>(As[192u + 56u + kg]);
      let a4 = vec4<f32>(As[256u + 56u + kg]);
      let a5 = vec4<f32>(As[320u + 56u + kg]);
      let a6 = vec4<f32>(As[384u + 56u + kg]);
      let a7 = vec4<f32>(As[448u + 56u + kg]);
      let w0 = vec4<f32>(trits(wb0, 24u)) * sc0;
      acc0_0 += f32(dot(w0, a0));
      acc0_1 += f32(dot(w0, a1));
      acc0_2 += f32(dot(w0, a2));
      acc0_3 += f32(dot(w0, a3));
      acc0_4 += f32(dot(w0, a4));
      acc0_5 += f32(dot(w0, a5));
      acc0_6 += f32(dot(w0, a6));
      acc0_7 += f32(dot(w0, a7));
      let w1 = vec4<f32>(trits(wb1, 24u)) * sc1;
      acc1_0 += f32(dot(w1, a0));
      acc1_1 += f32(dot(w1, a1));
      acc1_2 += f32(dot(w1, a2));
      acc1_3 += f32(dot(w1, a3));
      acc1_4 += f32(dot(w1, a4));
      acc1_5 += f32(dot(w1, a5));
      acc1_6 += f32(dot(w1, a6));
      acc1_7 += f32(dot(w1, a7));
      let w2 = vec4<f32>(trits(wb2, 24u)) * sc2;
      acc2_0 += f32(dot(w2, a0));
      acc2_1 += f32(dot(w2, a1));
      acc2_2 += f32(dot(w2, a2));
      acc2_3 += f32(dot(w2, a3));
      acc2_4 += f32(dot(w2, a4));
      acc2_5 += f32(dot(w2, a5));
      acc2_6 += f32(dot(w2, a6));
      acc2_7 += f32(dot(w2, a7));
      let w3 = vec4<f32>(trits(wb3, 24u)) * sc3;
      acc3_0 += f32(dot(w3, a0));
      acc3_1 += f32(dot(w3, a1));
      acc3_2 += f32(dot(w3, a2));
      acc3_3 += f32(dot(w3, a3));
      acc3_4 += f32(dot(w3, a4));
      acc3_5 += f32(dot(w3, a5));
      acc3_6 += f32(dot(w3, a6));
      acc3_7 += f32(dot(w3, a7));
    }
    workgroupBarrier();
  }
  { var v = acc0_0; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[0u * P.N + row0 + 0u] = v; } }
  { var v = acc0_1; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[1u * P.N + row0 + 0u] = v; } }
  { var v = acc0_2; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[2u * P.N + row0 + 0u] = v; } }
  { var v = acc0_3; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[3u * P.N + row0 + 0u] = v; } }
  { var v = acc0_4; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[4u * P.N + row0 + 0u] = v; } }
  { var v = acc0_5; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[5u * P.N + row0 + 0u] = v; } }
  { var v = acc0_6; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[6u * P.N + row0 + 0u] = v; } }
  { var v = acc0_7; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[7u * P.N + row0 + 0u] = v; } }
  { var v = acc1_0; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[0u * P.N + row0 + 1u] = v; } }
  { var v = acc1_1; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[1u * P.N + row0 + 1u] = v; } }
  { var v = acc1_2; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[2u * P.N + row0 + 1u] = v; } }
  { var v = acc1_3; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[3u * P.N + row0 + 1u] = v; } }
  { var v = acc1_4; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[4u * P.N + row0 + 1u] = v; } }
  { var v = acc1_5; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[5u * P.N + row0 + 1u] = v; } }
  { var v = acc1_6; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[6u * P.N + row0 + 1u] = v; } }
  { var v = acc1_7; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[7u * P.N + row0 + 1u] = v; } }
  { var v = acc2_0; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[0u * P.N + row0 + 2u] = v; } }
  { var v = acc2_1; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[1u * P.N + row0 + 2u] = v; } }
  { var v = acc2_2; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[2u * P.N + row0 + 2u] = v; } }
  { var v = acc2_3; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[3u * P.N + row0 + 2u] = v; } }
  { var v = acc2_4; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[4u * P.N + row0 + 2u] = v; } }
  { var v = acc2_5; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[5u * P.N + row0 + 2u] = v; } }
  { var v = acc2_6; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[6u * P.N + row0 + 2u] = v; } }
  { var v = acc2_7; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[7u * P.N + row0 + 2u] = v; } }
  { var v = acc3_0; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[0u * P.N + row0 + 3u] = v; } }
  { var v = acc3_1; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[1u * P.N + row0 + 3u] = v; } }
  { var v = acc3_2; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[2u * P.N + row0 + 3u] = v; } }
  { var v = acc3_3; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[3u * P.N + row0 + 3u] = v; } }
  { var v = acc3_4; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[4u * P.N + row0 + 3u] = v; } }
  { var v = acc3_5; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[5u * P.N + row0 + 3u] = v; } }
  { var v = acc3_6; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[6u * P.N + row0 + 3u] = v; } }
  { var v = acc3_7; v += subgroupShuffleXor(v, 1u); v += subgroupShuffleXor(v, 2u); v += subgroupShuffleXor(v, 4u); if (kg == 0u) { Y[7u * P.N + row0 + 3u] = v; } }
}
